pipeline {
  agent any
  stages {
    stage('test_2') {
      steps {
        sh '''pwd
cd pytest_demo
source /home/PJLAB/lijialun/.venv/bin/activate
pytest --alluredir=./allure-results'''
      }
    }

  }
}
