pipeline {
  agent any
  stages {
    stage('test_2') {
      steps {
        sh '''pwd
cd pytest_demo
source /home/PJLAB/lijialun/.venv/bin/activate
pytest --alluredir=./allure-results'''
      }
    }
    
  }
  post { 
    always { 
       allure includeProperties: false, jdk: '', results: [[path: 'pytest_demo_2/allure-results']]
    }
  }
}
